"""AG UI DevTask Schema — closed-loop agent-driven development.

A DevTask is the unit of work for the development agent loop:
  Slack message / Linear issue / GitHub issue → DevTask → code → PR → merged

Lifecycle:
  pending → implementing → validating → creating_pr →
  shepherding_ci → [responding_to_review →] completed | needs_human

State is persisted in the same DynamoDB store as IncidentState.
"""
from __future__ import annotations

import time
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


CURRENT_DEV_TASK_SCHEMA_VERSION = "1.0"


class DevTaskStatus(str, Enum):
    PENDING             = "pending"
    IMPLEMENTING        = "implementing"       # agent writing code
    VALIDATING          = "validating"         # running test/lint/typecheck suite
    CREATING_PR         = "creating_pr"        # opening PR on GitHub
    SHEPHERDING_CI      = "shepherding_ci"     # watching CI, auto-fixing failures
    RESPONDING_TO_REVIEW = "responding_to_review"  # addressing reviewer feedback
    COMPLETED           = "completed"          # PR merged or closed
    FAILED              = "failed"             # unrecoverable failure
    NEEDS_HUMAN         = "needs_human"        # blocked, needs engineer


class DevTaskSource(str, Enum):
    SLACK        = "slack"
    LINEAR       = "linear"
    GITHUB_ISSUE = "github_issue"
    MANUAL       = "manual"


class DevTaskPriority(str, Enum):
    URGENT = "urgent"
    HIGH   = "high"
    MEDIUM = "medium"
    LOW    = "low"


class DevTaskType(str, Enum):
    FEATURE      = "feature"
    BUG_FIX      = "bug_fix"
    REFACTOR     = "refactor"
    PERFORMANCE  = "performance"
    SECURITY     = "security"
    DEPENDENCY   = "dependency"
    DOCS         = "docs"
    TEST         = "test"


class ValidationResult(BaseModel):
    """Result of one validation pass (tests / lint / typecheck)."""
    iteration: int
    passed: bool
    test_output: str = ""
    lint_output: str = ""
    typecheck_output: str = ""
    errors: list[str] = Field(default_factory=list)
    files_changed: list[str] = Field(default_factory=list)
    duration_sec: float = 0.0
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class CIRun(BaseModel):
    """Snapshot of a single CI pipeline run on the PR."""
    run_id: str = ""
    status: str = ""          # pending | running | success | failure | cancelled
    conclusion: str = ""      # success | failure | neutral | skipped | timed_out
    failed_jobs: list[str] = Field(default_factory=list)
    fix_attempt: int = 0
    url: str = ""
    checked_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class ReviewComment(BaseModel):
    """A single review comment on the PR."""
    comment_id: str = ""
    author: str = ""
    body: str = ""
    file_path: str = ""
    line: int = 0
    resolved: bool = False
    agent_response: str = ""
    responded_at: str = ""


class DevTask(BaseModel):
    """Full development task state — persisted in DynamoDB."""
    model_config = {"extra": "allow"}

    # Identity
    task_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    schema_version: str = Field(default=CURRENT_DEV_TASK_SCHEMA_VERSION)
    org_id: str = Field(default="default")

    # Source
    source: DevTaskSource = DevTaskSource.MANUAL
    source_id: str = ""           # Slack message ts, Linear issue ID, GitHub issue #
    source_url: str = ""          # Deep link back to origin
    requested_by: str = ""        # User ID or handle

    # Task description
    title: str
    description: str
    task_type: DevTaskType = DevTaskType.FEATURE
    priority: DevTaskPriority = DevTaskPriority.MEDIUM

    # Affected scope (from production context)
    affected_services: list[str] = Field(default_factory=list)
    affected_files: list[str] = Field(default_factory=list)
    related_incident_ids: list[str] = Field(default_factory=list)   # linked incidents
    related_kg_nodes: list[str] = Field(default_factory=list)

    # Implementation plan (generated by agent before writing code)
    implementation_plan: str = ""
    files_to_create: list[str] = Field(default_factory=list)
    files_to_modify: list[str] = Field(default_factory=list)
    production_context_summary: str = ""   # what the agent learned from prod before coding

    # Lifecycle
    status: DevTaskStatus = DevTaskStatus.PENDING
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    duration_sec: float = 0.0

    # Validation history
    validation_iterations: int = 0
    max_iterations: int = 5
    validation_history: list[ValidationResult] = Field(default_factory=list)
    validation_passed: bool = False

    # PR
    pr_number: Optional[int] = None
    pr_url: str = ""
    pr_branch: str = ""
    pr_title: str = ""
    pr_description: str = ""

    # CI shepherding
    ci_runs: list[CIRun] = Field(default_factory=list)
    ci_fix_attempts: int = 0
    max_ci_fix_attempts: int = 3

    # Review
    review_comments: list[ReviewComment] = Field(default_factory=list)
    review_iterations: int = 0
    max_review_iterations: int = 3

    # Budget
    llm_calls_used: int = 0
    llm_calls_max: int = 30
    tool_calls_used: int = 0

    # Outcome
    merged: bool = False
    merge_commit: str = ""
    blocker_reason: str = ""    # populated when status=needs_human

    # TTL (DynamoDB, 60 days)
    ttl: int = Field(default_factory=lambda: int(time.time()) + 60 * 24 * 3600)

    def to_dynamo(self) -> dict[str, Any]:
        data = self.model_dump()
        data["pk"] = f"DEVTASK#{self.task_id}"
        data["sk"] = "STATE"
        data["gsi1pk"] = f"ORG#{self.org_id}"
        data["gsi1sk"] = self.started_at or ""
        data["gsi2pk"] = f"DEVSTATUS#{self.status.value}"
        data["gsi2sk"] = self.started_at or ""
        return data

    @property
    def budget_exhausted(self) -> bool:
        return self.llm_calls_used >= self.llm_calls_max

    @property
    def can_retry_validation(self) -> bool:
        return self.validation_iterations < self.max_iterations

    @property
    def can_retry_ci(self) -> bool:
        return self.ci_fix_attempts < self.max_ci_fix_attempts

    @property
    def can_retry_review(self) -> bool:
        return self.review_iterations < self.max_review_iterations
