"""Fix Engine — manages the lifecycle of a proposed fix from generation to verification.

This is the "execution arm" of the autonomous remediation system.
It handles:
  1. Storing proposed fixes (from CodeWorker.generate_fix)
  2. Applying fixes (rollback via kubectl OR code fix via GitHub PR)
  3. Tracking fix application status
  4. Triggering the verification loop after apply

Human-in-the-loop gate:
  Every fix requires human approval before application (requires_approval=True).
  The AGUI presents the fix proposal to the operator.
  Only after explicit approval does the system call apply_fix().

Fix lifecycle:
  PROPOSED → APPROVED → APPLYING → APPLIED → VERIFYING → VERIFIED | FAILED

Storage:
  In-process dict (production should use Redis/DB with TTL).
  Keyed by investigation_id.

Usage:
    engine = get_fix_engine()

    # Store a proposed fix after investigation
    engine.propose(investigation_id, fix_dict)

    # Operator approves via AGUI
    engine.approve(investigation_id, actor_id)

    # System applies the fix (called by AGUI /apply-fix endpoint)
    await engine.apply_fix(investigation_id, actor_id, devops_worker, itsm_worker)

    # Check status
    status = engine.get_status(investigation_id)
"""
from __future__ import annotations

import asyncio
import logging
import time
import uuid
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Optional

logger = logging.getLogger("sentinalai.fix_engine")


class FixStatus(str, Enum):
    PROPOSED = "proposed"
    APPROVED = "approved"
    REJECTED = "rejected"
    APPLYING = "applying"
    APPLIED = "applied"
    VERIFYING = "verifying"
    VERIFIED = "verified"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"


@dataclass
class ProposedFix:
    """A concrete, actionable fix proposal generated by the CodeWorker."""

    investigation_id: str
    incident_id: str
    fix_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])

    # Fix content
    fix_type: str = "none"           # rollback | code_fix | config_change | scale_up | none
    fix_description: str = ""
    confidence: float = 0.0
    risk_level: str = "medium"       # low | medium | high | critical
    requires_approval: bool = True

    # Immediate action (fast, safe — usually rollback)
    immediate_action: dict = field(default_factory=dict)

    # Permanent action (code PR or config change)
    permanent_action: Optional[dict] = None

    # Code fix details
    pr_title: str = ""
    pr_body: str = ""
    patch: str = ""
    repo: str = ""
    base_sha: str = ""

    # Lifecycle
    status: FixStatus = FixStatus.PROPOSED
    proposed_at: float = field(default_factory=time.time)
    approved_at: Optional[float] = None
    applied_at: Optional[float] = None
    approved_by: str = ""
    applied_by: str = ""

    # Application result
    apply_result: dict = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["status"] = self.status.value
        return d

    @classmethod
    def from_code_worker_result(
        cls,
        investigation_id: str,
        incident_id: str,
        code_worker_result: dict,
    ) -> "ProposedFix":
        """Build a ProposedFix from CodeWorker.generate_fix output."""
        immediate = code_worker_result.get("immediate_action", {})
        permanent = code_worker_result.get("permanent_action")

        return cls(
            investigation_id=investigation_id,
            incident_id=incident_id,
            fix_type=code_worker_result.get("fix_type", "none"),
            fix_description=code_worker_result.get("fix_description", ""),
            confidence=float(code_worker_result.get("confidence", 0)),
            risk_level=code_worker_result.get("risk_level", "medium"),
            requires_approval=code_worker_result.get("requires_approval", True),
            immediate_action=immediate,
            permanent_action=permanent,
            pr_title=code_worker_result.get("pr_title", ""),
            pr_body=code_worker_result.get("pr_body", ""),
            patch=code_worker_result.get("patch", ""),
            repo=code_worker_result.get("repo", ""),
            base_sha=code_worker_result.get("sha", ""),
        )


@dataclass
class FixApplication:
    """Result of applying a fix."""
    investigation_id: str
    fix_id: str
    actor_id: str
    applied_at: float
    action_taken: str       # "rollback" | "pr_created" | "kubectl_patch"
    success: bool
    result_detail: dict
    verification_started: bool = False


class FixEngine:
    """Manages proposed fixes and their application.

    Thread-safe for concurrent investigations (uses per-key asyncio locks).
    """

    def __init__(self) -> None:
        self._fixes: dict[str, ProposedFix] = {}
        self._applications: dict[str, FixApplication] = {}
        self._locks: dict[str, asyncio.Lock] = {}

    def propose(self, investigation_id: str, fix: ProposedFix) -> None:
        """Store a proposed fix. Overwrites any previous proposal for same investigation."""
        self._fixes[investigation_id] = fix
        logger.info(
            "Fix proposed: inv=%s fix_id=%s type=%s confidence=%.0f risk=%s",
            investigation_id, fix.fix_id, fix.fix_type, fix.confidence, fix.risk_level,
        )

    def propose_from_result(
        self,
        investigation_id: str,
        incident_id: str,
        code_worker_result: dict,
    ) -> ProposedFix:
        """Convenience: build + store a ProposedFix from CodeWorker output."""
        fix = ProposedFix.from_code_worker_result(
            investigation_id, incident_id, code_worker_result
        )
        self.propose(investigation_id, fix)
        return fix

    def approve(self, investigation_id: str, actor_id: str) -> bool:
        """Mark a fix as approved by a human operator."""
        fix = self._fixes.get(investigation_id)
        if not fix:
            logger.warning("approve: no fix found for investigation %s", investigation_id)
            return False
        if fix.status != FixStatus.PROPOSED:
            logger.warning(
                "approve: fix %s already in status %s", fix.fix_id, fix.status
            )
            return False
        fix.status = FixStatus.APPROVED
        fix.approved_at = time.time()
        fix.approved_by = actor_id
        logger.info("Fix approved: inv=%s fix_id=%s by=%s", investigation_id, fix.fix_id, actor_id)
        return True

    def reject(self, investigation_id: str, actor_id: str, reason: str = "") -> bool:
        """Mark a fix as rejected by a human operator."""
        fix = self._fixes.get(investigation_id)
        if not fix:
            return False
        fix.status = FixStatus.REJECTED
        fix.apply_result = {"rejected_by": actor_id, "reason": reason}
        logger.info("Fix rejected: inv=%s by=%s reason=%s", investigation_id, actor_id, reason)
        return True

    async def apply_fix(
        self,
        investigation_id: str,
        actor_id: str,
        devops_worker: Any,
        itsm_worker: Any,
        incident_id: str = "",
    ) -> FixApplication:
        """Apply an approved fix.

        Must be approved before calling this method.
        Creates an asyncio lock per investigation to prevent double-apply.
        """
        # Ensure we have a per-investigation lock
        if investigation_id not in self._locks:
            self._locks[investigation_id] = asyncio.Lock()

        async with self._locks[investigation_id]:
            fix = self._fixes.get(investigation_id)
            if not fix:
                raise ValueError(f"No proposed fix for investigation {investigation_id}")
            if fix.status == FixStatus.APPLYING:
                raise ValueError(f"Fix {fix.fix_id} is already being applied")
            if fix.status not in (FixStatus.APPROVED,):
                raise ValueError(
                    f"Fix {fix.fix_id} must be APPROVED before applying (current: {fix.status})"
                )

            fix.status = FixStatus.APPLYING
            fix.applied_by = actor_id

            try:
                application = await self._do_apply(fix, devops_worker, itsm_worker, actor_id)
                fix.status = FixStatus.APPLIED
                fix.applied_at = application.applied_at
                fix.apply_result = application.result_detail
                self._applications[investigation_id] = application
                logger.info(
                    "Fix applied: inv=%s fix_id=%s action=%s success=%s",
                    investigation_id, fix.fix_id, application.action_taken, application.success,
                )
                try:
                    from supervisor.metrics_dashboard import get_dashboard_engine
                    get_dashboard_engine().update_outcome(
                        investigation_id, fix_applied=application.success
                    )
                except Exception:
                    pass
                return application

            except Exception as exc:
                fix.status = FixStatus.FAILED
                fix.apply_result = {"error": str(exc)}
                logger.error("Fix application failed: inv=%s error=%s", investigation_id, exc)
                application = FixApplication(
                    investigation_id=investigation_id,
                    fix_id=fix.fix_id,
                    actor_id=actor_id,
                    applied_at=time.time(),
                    action_taken="failed",
                    success=False,
                    result_detail={"error": str(exc)},
                )
                self._applications[investigation_id] = application
                return application

    async def _do_apply(
        self, fix: ProposedFix, devops_worker: Any, itsm_worker: Any, actor_id: str
    ) -> FixApplication:
        """Execute the actual fix action."""
        action_taken = "none"
        result_detail: dict = {}

        if fix.fix_type == "rollback":
            imm = fix.immediate_action
            action_taken = "rollback"
            # Call devops worker to rollback
            result = devops_worker.execute("rollback_deployment", {
                "service": imm.get("service", ""),
                "repo": fix.repo,
                "sha": fix.base_sha,
                "command": imm.get("command", ""),
                "actor_id": actor_id,
            })
            result_detail = result or {}

        elif fix.fix_type == "code_fix" and fix.pr_title:
            action_taken = "pr_created"
            result = devops_worker.execute("create_fix_pr", {
                "repo": fix.repo,
                "title": fix.pr_title,
                "body": fix.pr_body,
                "patch": fix.patch,
                "base_sha": fix.base_sha,
                "actor_id": actor_id,
            })
            result_detail = result or {}

        elif fix.fix_type == "scale_up":
            action_taken = "kubectl_patch"
            imm = fix.immediate_action
            result = devops_worker.execute("scale_service", {
                "service": imm.get("service", ""),
                "replicas": imm.get("replicas", 2),
                "actor_id": actor_id,
            })
            result_detail = result or {}

        else:
            action_taken = "manual_required"
            result_detail = {"message": "Manual fix required — no automated action available"}

        success = "error" not in result_detail
        return FixApplication(
            investigation_id=fix.investigation_id,
            fix_id=fix.fix_id,
            actor_id=actor_id,
            applied_at=time.time(),
            action_taken=action_taken,
            success=success,
            result_detail=result_detail,
        )

    def get_status(self, investigation_id: str) -> dict[str, Any]:
        """Get current fix status for an investigation."""
        fix = self._fixes.get(investigation_id)
        if not fix:
            return {"status": "no_fix", "investigation_id": investigation_id}

        application = self._applications.get(investigation_id)
        return {
            "investigation_id": investigation_id,
            "fix_id": fix.fix_id,
            "fix_type": fix.fix_type,
            "status": fix.status.value,
            "fix_description": fix.fix_description,
            "confidence": fix.confidence,
            "risk_level": fix.risk_level,
            "requires_approval": fix.requires_approval,
            "approved_by": fix.approved_by,
            "applied_by": fix.applied_by,
            "proposed_at": fix.proposed_at,
            "approved_at": fix.approved_at,
            "applied_at": fix.applied_at,
            "apply_result": fix.apply_result,
            "application": asdict(application) if application else None,
        }

    def get_fix(self, investigation_id: str) -> Optional[ProposedFix]:
        return self._fixes.get(investigation_id)

    def mark_verified(self, investigation_id: str, verification_result: dict) -> None:
        """Called by VerificationLoop when service is stable post-fix."""
        fix = self._fixes.get(investigation_id)
        if fix:
            fix.status = FixStatus.VERIFIED
            fix.apply_result["verification"] = verification_result
            logger.info("Fix verified: inv=%s", investigation_id)

    def mark_failed_verification(self, investigation_id: str, reason: str) -> None:
        """Called by VerificationLoop when service does not stabilize."""
        fix = self._fixes.get(investigation_id)
        if fix:
            fix.status = FixStatus.FAILED
            fix.apply_result["verification_failure"] = reason
            logger.warning("Fix verification failed: inv=%s reason=%s", investigation_id, reason)


# ── Global singleton ──────────────────────────────────────────────────────────

_fix_engine: Optional[FixEngine] = None


def get_fix_engine() -> FixEngine:
    global _fix_engine
    if _fix_engine is None:
        _fix_engine = FixEngine()
    return _fix_engine
